version: '3'
services:
  dex:
    build:
      context: ./dex
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "3001:3001"
