name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  dex-build:
    name: Build and Test Dex Folder
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: cd dex && yarn install
      - run: cd dex && yarn build # Replace with your actual build command if different
      - run: cd dex && yarn test  # Replace with your actual test command if different

  server-build:
    name: Build and Test Server Folder
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: cd server && yarn install
      - run: cd server && yarn build # Replace with your actual build command if different
      - run: cd server && yarn test  # Replace with your actual test command if different
